# Generated by Django 3.0.7 on 2021-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('credit', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=30)),
            ],
        ),
    ]
