# Generated by Django 3.0.7 on 2021-05-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
