# Generated by Django 3.0.7 on 2021-05-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20210522_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='value',
        ),
    ]
