# Generated by Django 3.0.7 on 2021-05-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_auto_20210521_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='rollno',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(max_length=1),
        ),
    ]
