# Generated by Django 3.0.7 on 2021-05-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_auto_20210522_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='grades',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='semesters',
            new_name='semester',
        ),
    ]
